[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = [
    "."
]

[tool.ruff]
target-version = "py310"
select = [
    "B",
    "C",
    "E",
    "F",
    "I",
    "UP",
]
ignore = [
    "C901", # Complexity
    "E501", # Line length
    "B905",
]
unfixable = [
    "B007", # Loop control variable not used within the loop body
]
